# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mova-shlink

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mova21.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0474615217004258a623aae3acb4de78 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_11e3768a1ec04f969502573db36617fe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mova21.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0474615217004258a623aae3acb4de78 }}/shlink:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mova-shlink'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_31cd67acc6a740f195f929eef3657ac7 }}
        images: 'mova21.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0474615217004258a623aae3acb4de78 }}/shlink:${{ github.sha }}'